#!/usr/bin/awk -f

function sleep (secs){
	if (!nosleep && 0 != system("sleep " secs)){
		exit 10
	}
}

function my_rnd (){
	if (rand() < threshold)
		return 0.0
	else
		return rand()
}

BEGIN {
	threshold = ARGV [1] + 0.0
	fake_cmd  = ARGV [2]

	nosleep   = ARGV [1] ~ /ns/
	nopostfail = ARGV [1] ~ /nopostfail/

	ARGV [1] = "-"
	ARGV [2] = ""

	srand()

#	sleep(my_rnd())
}

{
	if (my_rnd() == 0.0) {
		sleep(0.1)
		exit 1
	}

	sleep(my_rnd())

	print " " $0

	if (!nopostfail && my_rnd() == 0.0) {
		sleep(0.1)
		exit 1
	}

	print "success"
	print ""
	fflush()
}
