#!/usr/bin/awk -f

function sleep (secs){
	if (system("sleep " secs)){
		exit 10
	}
}

BEGIN {
	fake_node = ARGV [1]
	fake_cmd  = ARGV [2]

	ARGV [1] = "-"
	ARGV [2] = ""

	if (fake_node ~ /fail/){
		fail_pause = fake_node + 0
		sleep(fail_pause)
#		print "Me failed!" > "/dev/stderr"
		exit 1
	}

#	print "fake_node=" fake_node > "/dev/stderr"
}

$1 == fake_node {
	sleep(0.5)
	exit 1
}

{
	sleep(1)
	print " " $0
	print "success"
	print ""
	fflush()
}
