#!/bin/sh

# Calculate 1/$1 values in 3 parallel subprocesses.
# Dependency graph of tasks comes from stdin.
# Tasks 7, 8, 9 and 10 will be marked as failed
# due to task 0 failure. See cmd for details.

paexec -s -l -c "`pwd`/cmd" -n +3 <<EOF
1 2
2 3
3 4
4 5
5 0
0 7
7 8
8 9
5 10
10 11
11 12
EOF
