#!/usr/bin/env sh

# Obtains all substrings in parallel using 3 subprocesses.
# Subprocesses are run on the same host where paexec is run.
# Output lines are prepanded with task number (-l)
# and process pid (-p).
# In the end of task, an empty line is added (-e)
# Output is sliced.
paexec -lpe -c "`pwd`/cmd" -n +3 <<EOF
My English is awesome.
Who is absent?
My name is Aleksey.
I was born in USSR.
London is a capital of Great Britain.
Who is on duty today? :-)
EOF
