#!/bin/sh

# Converts all strings to upper case in parallel.
# Subprocesses are run on the same host where paexec is run.
# Input may contains empty lines.

input (){
    cat <<'EOF'
My English is awesome.
Who is absent?
My name is Aleksey.
I was born in USSR.
London is a capital of Great Britain.
Who is on duty today? :-)
EOF
}

input | paexec -c "`pwd`/cmd" -n +2 | cut -b 2-
