#!/bin/sh

# here we compile .c sources in parallel on two hosts: localhost and chen
../../paexec -c 'env CC=gcc CFLAGS=-O2 ./cc_wrapper_cmd' \
             -n 'localhost chen' <<EOF
func1.c
func2.c
func3.c
EOF
