INSCRIPTS   =	make_package_cmd make_package_cmd__xxx_failed

SCRIPTS     =	${INSCRIPTS}
FILES      !=	echo make_package_tasks*

FILESDIR    =	${EGDIR}/${.CURDIR:T}
SCRIPTSDIR ?=	${FILESDIR}

.include <mkc.subprj.mk>
