#!/usr/bin/env sh

# Written by Aleksey Cheusov <vle@gmx.net>
# Public domain

shift # skip node

unset PAEXEC_EOT

# unset variables used in regression tests
unset ZZZZ
unset YYYY
unset CCCC 

#
eval "$@"
